[package]
name = "god-ai"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# HTTP library
reqwest = { version = "0.12", features = ["json"] }
# Async loops
tokio = { version = "1", features = ["full"] }
# Discord
serenity = { version = "0.12", default-features = false, features = [
  "builder",
  "client",
  "gateway",
  "collector",
  "http",
  "rustls_backend",
  "model",
] }
# JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unescape = "0.1"
futures = "0.3"
async-trait = "0.1"
const_format = "0.2"
once_cell = "1"
ollama-rs = "0.2"
clap = { version = "4", features = ["derive"] }
